# Generated by Django 4.1.7 on 2023-05-14 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shop', '0011_user2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('imageuser', models.ImageField(blank=True, null=True, upload_to='userim/')),
                ('money', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='User2',
        ),
    ]
