# Generated by Django 4.1.7 on 2023-05-14 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_userprofile_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='rating',
            new_name='money',
        ),
    ]
